package:
  name: oce
  version: 0.18.3

source:
  git_url: https://github.com/tpaviot/oce.git
  git_tag: OCE-0.18.3

build:
  detect_binary_files_with_prefix: True
  number: 3
  features:
    - vc9               [win and py27]
    - vc14              [win and py35]

requirements:
  build:
    - ninja ==1.8.2
    - gl2ps ==1.3.8
    - freeimageplus ==3.17.0
    - tbb ==2018_20171205
    - python
    - freetype ==2.8.1
    - cmake ==3.8.0

  run:
    - gl2ps ==1.3.8
    - freeimageplus ==3.17.0
    - tbb >=2017_20170226
    - freetype >=2.7

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
