package:
  name: oce
  version: 0.17.3

source:
  fn: OCE-0.17.3.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-0.17.3.tar.gz

build:
  detect_binary_files_with_prefix: True
  number: 1
  features:
    - vc9               [win and py27]
    - vc14              [win and py35]

requirements:
  build:
    - ninja
    - gl2ps
    - freeimage
    - tbb
    - python
    - freetype
    - cmake

  run:
    - gl2ps
    - freeimage
    - tbb
    - freetype

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
